[project]
name = "Dota2RuneRemainder"

[general]
    # path to your dota installation. This path must point to "....\\dota 2 beta\\game\\dota"
    # it is extremely important to use " (NOT ') and to use double slashes \\ (NOT \ or /)
    dota2path = "your path\\SteamLibrary\\steamapps\\common\\dota 2 beta\\game\\dota"

[[events]]
    offset = 15
    sentence = "Wisdom rune spawing"
    recurring = true
    name = "Wisdom"
    amount = 420

[[events]]
    offset = 15
    sentence = "Gold rune and Lotus  spawing"
    recurring = true
    name = "Gold and lotus"
    amount = 180

[[events]]
    offset = 15
    sentence = "Tormentor spawing"
    recurring = false
    name = "Tormentor"
    amount = 1200